# Site settings
title: ©olling
email: lloyd@colling.co
description: "Thoughts and work"
baseurl: ""
url: "http://colling.co"
twitter_username: lloyd.colling
github_username:  lloydcolling

# Build settings
markdown: kramdown
permalink: pretty
