# Site settings
title: ©olling - work
email: lloyd@colling.co
description: "thoughts and work samples"
baseurl: ""
url: "http://colling.co"
twitter_username: lloyd.colling
github_username:  lloydcolling

# Build settings
markdown: kramdown
permalink: pretty
